version: "3.2"

services:
  click-quack-backend:
    image: click-and-quacks:0.0.1
    container_name: backend_click-quack
    environment:
      NODE_TEST: Meu_valor
    volumes:
      - /var/quack/count.txt:/usr/app/count.txt
    ports:
      - "5000:5000"
